name: RankGUI
main: VsrStudio\RankGUI\RankGUI
version: 1.0.0
api: 5.0.0
author: VsrStudio
description: Plugin to display rank and rules in GUI
depend: 
  - InvMenu
  - CustomSizedInvMenu

commands:
  ranklist:
    description: Open the rank list gui
    permission: rankgui.use
    aliases: [rank]
  rules:
    description: View the server rules
    permission: rulesgui.use

permissions:
  rankgui.use:
    default: true
  rulesgui.use:
    default: true
